# Generated by Django 4.1.7 on 2023-04-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('semail', models.CharField(max_length=70)),
                ('spassword', models.CharField(max_length=30)),
                ('scpassword', models.CharField(max_length=30)),
                ('saddress', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=30)),
                ('scity', models.CharField(max_length=50)),
                ('sstate', models.CharField(max_length=50)),
                ('spincode', models.CharField(max_length=20)),
                ('scountry', models.CharField(max_length=50)),
                ('scompany', models.CharField(max_length=100)),
            ],
        ),
    ]
