# Generated by Django 4.1.7 on 2023-04-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=80)),
                ('uemail', models.CharField(default='0', max_length=50)),
                ('unumber', models.CharField(max_length=50)),
                ('upassword', models.CharField(default='0', max_length=30)),
                ('uconfirmpassword', models.CharField(default='0', max_length=30)),
            ],
        ),
    ]
