# Generated by Django 4.1.7 on 2023-08-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custaddress', models.CharField(max_length=200)),
                ('custcity', models.CharField(max_length=50)),
                ('custpincode', models.CharField(max_length=10)),
            ],
        ),
    ]
